### ISSUE TITLE
Deprecated dependent package

### ISSUE THREAD

**Issue by yeqiaoling** [xunzheng/notears#2]
Hi Xun,

This is Qiaoling. I'm using notears module! While installing cppext by command 'python setup.py install', I occurred the following problem:

```
warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'g++' failed with exit status 1
```

I attached the image of error at the end. Do you happen to know how to solve it in order to full the full version of notears?

Thanks!
Qiaoling

<img width="708" alt="Screen Shot 2019-07-30 at 9 20 28 PM" src="https://user-images.githubusercontent.com/15239994/62183839-885aa000-b310-11e9-869e-93c17147ca39.png">

**Comment by xunzheng** [comment]
Hi Qiaoling,

Thanks for posting. I haven't experienced this error before but looks like there is a related issue [here](https://github.com/igraph/python-igraph/issues/208). Could you try solutions suggested there and let me know if it worked?

**Comment by yeqiaoling** [comment]
Great! Add 'xtra_link_args=["-stdlib=libc++"]' worked. I can now use the NOTEARS.
