### ISSUE TITLE
errors in "error: Unable to find vcvarsall.bat"

### ISSUE THREAD

**Issue by gmeng92** [xunzheng/notears#3]
Hi Xunzheng,

I just met this problem when I am trying to install the cppext tools for optimization.
![image](https://user-images.githubusercontent.com/36212932/62659074-041ba480-b930-11e9-8734-99f249558fe0.png) 
 It seems that the notears with l1-regularization cannot run without cppext. The typical error is like the following:
![image](https://user-images.githubusercontent.com/36212932/62659228-6f657680-b930-11e9-96d0-231ec89fee5d.png)

Have you met those problems before?  I am looking forward to your reply.

ps: I used Python 3.7 version to install the setup.py. 

Best,

Gemeng

**Comment by xunzheng** [comment]
Hi Gemeng,

Thanks for reporting. I haven't tested the code on Windows, but looks like [this post](https://devblogs.microsoft.com/python/unable-to-find-vcvarsall-bat/) might be helpful. Let me know if it helps.

**Comment by gmeng92** [comment]
Thanks. I  thought the missing file is related to those codes. It looks more like another issue. I will check if I can fix it and come back updating

**Comment by gmeng92** [comment]
Hi Xun,

Here is the latest update. I install the Microsoft Visual Studio 2019 with c++ compiler and delete"extra_compile_args" in the setup.py.  " python setup.py install" will no long error and the live demo can run on Jupyter Notebook right now. Thanks for your help.
