### ISSUE TITLE
why using non-negative box constraint?

### ISSUE THREAD

**Issue by lihebi** [xunzheng/notears#5]
When optimizing the sub-problem, the referenced code takes some non-negative bounds `bnds`. But as I understand, `W` can take negative values. The simulated models also contain negative weights as ground truth.

Is there any rationale behind this bound?

https://github.com/xunzheng/notears/blob/968da1482f466a2a54621d4264c1724d5e0b2394/src/notears.py#L65-L71

**Comment by lihebi** [comment]
I see `w_est` is separated into two `d`x`d` parts representing "positive" and "negative", making it a total of `2`x`d`x`d` vector. I was confusing about this too, but now it makes sense.

Is this separation useful for sub-problem optimization or something?

**Comment by xunzheng** [comment]
Yes, it transforms the L1 norm sum(abs(w)) into a linear function sum(w_pos - w_neg) with box constraints w_pos >= 0, w_neg >= 0. This makes life easier since L-BFGS-B can readily handle box constraints.
