### ISSUE TITLE
w_est  = np.zeros(2 * d * d)

### ISSUE THREAD

**Issue by Foyn** [xunzheng/notears#8]
Hi! Thank you for sharing the program of the wonderful idea. But i have a small problem about the code. 
**_w_est, rho, alpha, h = np.zeros(2 * d * d), 1.0, 0.0, np.inf_**  
I can't understand that why there should be **2** * d * d instead of d*d? If the w_est is d * d, then it is the adjacent matrix, and there is no need to definite the _**_adj(w)**_.

**Comment by Foyn** [comment]
oh, i guess i may understand your great design.  
w_est are defined with 2 parts, (**w_pos**, **w_neg**), 
the possibility that these edges exist or do not exist correspond to **w_pos**, **w_neg** respectively. 
When **w_pos** - **w_neg** < threshhold, then these edges will be eliminated. 
This step is the post-processing step which estimates of coefficients via hard thresholding.

**Comment by xunzheng** [comment]
Yes, this is a way to rewrite L1 regularizer (||w||_1) as a linear objective (||w_pos - w_neg||_1 = sum(w_pos) + sum(w_neg)) + box constraint (w_pos >= 0, w_neg >= 0).
