### ISSUE TITLE
Choice of parameters

### ISSUE THREAD

**Issue by gmeng92** [xunzheng/notears#9]
Hi Xun,

Thanks for sharing and updating your codes. I carefully go through your paper and the supplementary materials but cannot found the rationale of the model selection, i.e. the choice of lambda1in your work. How would you suggest regarding this issue when applying the model to real data instead of the simulation data sets in which we already have some hints about their ground truth? Have you tried any model selection approaches like AIC or BIC in your experiments?

**Comment by YinghuaGao** [comment]
Hi, gmeng92,

I am also intersted in this paper and confused about the details of experiments. Can we discuss them further ? Hope you can contact me and this is my email: yhgao18@gmail.com

**Comment by xunzheng** [comment]
The choice of lambda1 would depend on the number of variables (d), number of samples (n), and the sparsity of the graph (s0). One empirical way is to look at the density of the estimated graph and see if that matches prior knowledge. More principled approach would include model selection criteria like AIC/BIC, or stability selection, etc.
